spring.application.name=IssuePlanet

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=web
spring.datasource.password=7898
spring.datasource.url=jdbc:mariadb://192.168.10.132:3306/care

# mybatis framework setting
mybatis.mapper-locations=/mappers/*.xml

# JSP settings
spring.mvc.view.prefix=/jsp/
spring.mvc.view.suffix=.jsp

# file settings
spring.servlet.multipart.max-file-size=10MB

# 이미지가 저장될 실제 로컬 경로 (원하시는 폴더 경로로 수정하세요)
file.upload-path=D:/Program Files/cording/workspace/IssuePlanet/uploads

# 웹에서 접근할 주소 설정
spring.web.resources.static-locations=file:///D:/Program Files/cording/workspace/IssuePlanet/uploads

# server port settings
server.port=80